### ISSUE TITLE
Connection cannot be stablished err="failed to add credential got response code 406"

### ISSUE THREAD

**Issue by Atharex** [anchore/harbor-scanner-adapter#26]
I also got this error mentioned in #9 

```
time="2020-06-23T06:54:16Z" level=debug msg="sending request" URL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/registries" method=POST
time="2020-06-23T06:54:16Z" level=debug msg="api call duration" duration=693.580923ms
time="2020-06-23T06:54:16Z" level=debug msg="anchore API response" contentLength=572 contentType=application/json requestMethod=POST requestURL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/registries?validate=true" status="406 NOT ACCEPTABLE" statusCode=406
time="2020-06-23T06:54:16Z" level=error msg="unexpected error response from anchore adding registry credential" receivedResponse="{\n  \"detail\": {\n    \"error_codes\": []\n  },\n  \"httpcode\": 406,\n  \"message\": \"cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://harbor.external.domain.com,robot$Anchore-588ceb4f-b51e-11ea-a2dc-06f6c9781c39) - exception: HTTPSConnectionPool(host='harbor.external.domain.com', port=443): Max retries exceeded with url: /v2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7b09ce4978>: Failed to establish a new connection: [Errno -2] Name or service not known',))\"\n}\n" receivedStatusCode=406
time="2020-06-23T06:54:16Z" level=error msg="failed executing the scan request" err="failed to add valid credentials to anchore for registry"
time="2020-06-23T06:54:16Z" level=error msg="returning error response" code=500 message="failed to add valid credentials to anchore for registry"
```

The credentials and the request are correctly passed from Harbor to Anchore with the adapter, but the reverse lookup is not possible, since Anchore tries to add the Harbor registry from the external URL configured in the helm chart. 
**https://harbor.external.domain.com**

This will not work, because the external Harbor URL is not reachable from inside the anchore pod, unless you manually set up DNS entries. 
**(Failed to establish a new connection: [Errno -2] Name or service not known',)**

Is there a way to pass the reverse-lookup address of Harbor to Anchore? Something resolvable from within the Anchore pod (e.g. http://harbor-harbor-core.harbor.svc.cluster.local:80/)

**Comment by zhill** [comment]
hi @Atharex , apologies for the long delay in a response. The URL used by the adapter to tell Anchore how to reach Harbor comes in via the API request from Harbor to the adapter. You can select an option during adapter setup in Harbor that tells it to use the internal address instead of the external.

See: https://goharbor.io/docs/2.0.0/administration/vulnerability-scanning/pluggable-scanners/

**Comment by Atharex** [comment]
Thanks @zhill that solved that problem! Now I got another one...

My Harbor instance is not running under the default namespace, but under a harbor namespace. When I take a look at the request the adapter is sending to anchore I see that the registry URL is already premade to the default namespace. 
`time="2020-11-09T19:38:41Z" level=debug msg="scan request" request="{\"registry\":{\"url\":\"http://harbor-harbor-core:80\",\"authorization\":\"[REDACTED]\"},\"artifact\"...`

I presume this is the problem, as I am getting errors from Anchore after I request the image analysis (but the registry add call seems to succeeded nonetheless)
```
time="2020-11-09T19:38:41Z" level=debug msg="sending request" URL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/registries/harbor-harbor-core:80/library/nc-centos7" method=PUT
time="2020-11-09T19:38:41Z" level=debug msg="api call duration" duration=106.085109ms
time="2020-11-09T19:38:41Z" level=debug msg="anchore API response" contentLength=393 contentType=application/json requestMethod=PUT requestURL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/registries/harbor-harbor-core:80/library/nc-centos7?validate=false" status="200 OK" statusCode=200
time="2020-11-09T19:38:41Z" level=debug msg="successfully added registry credential to anchore"
time="2020-11-09T19:38:41Z" level=info msg="requesting image analysis" request="{{{harbor-harbor-core:80/library/nc-centos7@sha256:210882bd8f11c010a98b0c48598d9a78feabe6b904414415e3df5b8f008d40d3 harbor-harbor-core:80/library/nc-centos7:210882bd8f11c010a98b0c48598d9a78feabe6b904414415e3df5b8f008d40d3 2020-11-09T19:38:41Z}} docker map[]}"
time="2020-11-09T19:38:41Z" level=debug msg="sending request to anchore api" method=post url="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/images"
time="2020-11-09T19:38:41Z" level=debug msg="sending request" URL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/images" method=POST
time="2020-11-09T19:38:42Z" level=debug msg="api call duration" duration=628.450154ms
time="2020-11-09T19:38:42Z" level=debug msg="anchore API response" contentLength=886 contentType=application/json requestMethod=POST requestURL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/images" status="400 BAD REQUEST" statusCode=400
time="2020-11-09T19:38:42Z" level=error msg="Could not submit image for analysis request failed with status 400"
```


Is there a way for me to configure the registry URL within the adapter? Or at least to add the namespace to the URL?

**Comment by zhill** [comment]
@Atharex I'll have to take a look, but I think there are more config options in the harbor deployment to tell it what urls to use in the internal space as well. Looks like an issue here in their chart that doesn't account for the namespace itself: https://github.com/goharbor/harbor-helm/blob/master/templates/_helpers.tpl#L483

One option in the adapter is to handle the namespace update there. Are you deploying the adapter in the same namespace as harbor or as Anchore?

**Comment by Atharex** [comment]
I have the adapter running under the same namespace as harbor. 

```
NAMESPACE      NAME                                       TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                               AGE
anchore        anchore-anchore-engine-api                 ClusterIP      10.88.165.81    <none>         8228/TCP                              3h46m
harbor         harbor-harbor-core                         ClusterIP      10.86.208.5     <none>         80/TCP                                3h43m
harbor         harbor-scanner-anchore                     ClusterIP      10.88.194.132   <none>         8080/TCP                              163m
```

**Comment by blka** [comment]
seems like i had some similar problem, 
my setup using one docker daemon:
- harbor (standard setup with charts only and fix on nginx cause we are behind google LB)
- anchore engine with extra network setup in compose:
```
networks:
  anchore:
    external: true
  harbor_harbor:
    external: true
```
because of this, u need to create this networks before you're up anchore-engine compose file, in my case it's
```
docker network create harbor_harbor
docker network create anchore
```

this is full compose with networks added ( cause each (??) anchore service comunicate with "core" service from harbor and i want to pull images directly harbor <=> anchore without going over loadbalancer)

```
# This is a docker-compose file for development purposes. It refereneces unstable developer builds from the HEAD of master branch in https://github.com/anchore/anchore-engine
# For a compose file intended for use with a released version, see https://docs.anchore.com/current/docs/engine/quickstart/
#
---
version: '2.1'
volumes:
  anchore-db-volume:
    # Set this to 'true' to use an external volume. In which case, it must be created manually with "docker volume create anchore-db-volume"
    external: true
 
services:
  # The primary API endpoint service
  api:
    image: anchore/anchore-engine:v0.8.2
    networks:
      - harbor_harbor
      - anchore
    depends_on:
      - db
      - catalog
    ports:
      - "8228:8228"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=api
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_PASSWORD=dbpass
    command: ["anchore-manager", "service", "start", "apiext"]
 
  # Catalog is the primary persistence and state manager of the system
  catalog:
    image: anchore/anchore-engine:v0.8.2
    networks:
      - harbor_harbor
      - anchore
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    expose:
      - 8228
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=catalog
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_PASSWORD=dbpass
    command: ["anchore-manager", "service", "start", "catalog"]
  queue:
    image: anchore/anchore-engine:v0.8.2
    networks:
      - harbor_harbor
      - anchore
    depends_on:
      - db
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=queue
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_PASSWORD=dbpass
    command: ["anchore-manager", "service", "start", "simplequeue"]
  policy-engine:
    image: anchore/anchore-engine:v0.8.2
    networks:
      - harbor_harbor
      - anchore
    depends_on:
      - db
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=policy-engine
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_PASSWORD=dbpass
    command: ["anchore-manager", "service", "start", "policy_engine"]
  analyzer:
    image: anchore/anchore-engine:v0.8.2
    networks:
      - harbor_harbor
      - anchore
    depends_on:
      - db
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=analyzer
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_PASSWORD=dbpass
    volumes:
      - /analysis_scratch
    command: ["anchore-manager", "service", "start", "analyzer"]
  db:
    image: "postgres:9"
    networks:
      - anchore
    volumes:
      - anchore-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dbpass
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
networks:
  anchore:
    external: true
  harbor_harbor:
    external: true
```

and the last one, anchore-adapter, allowed to comunicate with harbor_harbor network and anchore + logging to file by using syslog from harbor compose:

```
version: '2.3'
services:
  anchore-adapter:
    container_name: anchore-adapter
    image: anchore/harbor-scanner-adapter:1.0.1
    restart: always
    cap_drop:
      - ALL
    dns_search: .
    networks:
      - harbor_harbor
      - anchore
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "anchore-adapter"
    env_file:
      ./env
networks:
  harbor:
    external: true
  anchore:
    external: true
```
by using this setup, your logs are in /var/log/harbor/anchore-adapter.log.

env file should be placed in the same directory as adapter's compose file:

env file:
```
SCANNER_ADAPTER_LOG_LEVEL=info
#this means you can connect to anchore-engine api inside docker network (anchore services are linked to "harbor" network)
ANCHORE_ENDPOINT=http://api:8228
ANCHORE_USERNAME=admin
ANCHORE_PASSWORD=adminpassword
ANCHORE_CLIENT_TIMEOUT_SECONDS=60
ANCHORE_FILTER_VENDOR_IGNORED=false
 
SCANNER_ADAPTER_FULL_VULN_DESCRIPTIONS=true
# this is needed, when you run harbor and anchore on the same docker
SCANNER_ADAPTER_REGISTRY_VALIDATE_CREDS=false
SCANNER_ADAPTER_REGISTRY_TLS_VERIFY=false
```

and the last last one :)

![image](https://user-images.githubusercontent.com/14985010/99807126-51308380-2b3f-11eb-9f1d-2000bd288bae.png)


enjoy!
